### ISSUE TITLE
Remake the UI

### ISSUE THREAD

**Issue by the-marenga** [the-marenga/sf-scrapbook-helper#11]
The UI looks bad and has been shown to cause errors in at least one case before. Switching to another framework like Qt is probably the better choice

**Comment by the-marenga** [comment]
Turns out QT looks about as bad as egui and is like 60 times more complicated. I might just have to learn how to make egui look less bad I guess

**Comment by Alleexxi** [comment]
You could take a look at https://iced.rs

**Comment by the-marenga** [comment]
Thanks for the suggestion! Looks pretty good from what I can see so far, I will give that a try

**Comment by the-marenga** [comment]
> You could take a look at https://iced.rs

That was an amazing suggestion! Thanks again, I really liked working with that. It is much simpler, better looking and has better async support than egui. Really improved this project by a lot
