### ISSUE TITLE
HOF custom start page

### ISSUE THREAD

**Issue by Jirkaon** [the-marenga/sf-scrapbook-helper#12]
Hello,
so in the end I came with feature(s) which will be really helpful. For higher levels (let’s say lvl 300+) you usually don’t need the lower level players (lvl 10, 20, 30…), because you already have their items in your scrapbook. So the feature(s) would be:

1. Manually specify the starting page of crawling and crawl from that point.
2. Ability to start crawling from the top of HOF (from the best player) to the bottom. 
3. Crawl from the manually specified page up or down.

I know, it’ll be a guess work on some level with the page from where you want to start the crawl, but it can speed up the searching. 

It could be helpful for higher levels if you need only few items and you know that the lower levels can’t have them. 

But it could be meaningless to some degree if you come up with some type of sharing of the crawled HOF, as you mentioned. In this situation it could be useful for uncrawled and unshared servers.

**Comment by Usaksport** [comment]
Or maybe it could also possible to set a start level instead only the max level how it is right now. And additionally just to mention it you did a very great job @the-marenga

**Comment by Usaksport** [comment]
That also sounds very good. But will it still be as accurate as before? Since many players also change their equipment in between. Or is the file updated every time? Or how is it planned? Thanks.

**Comment by the-marenga** [comment]
I am planing to keep the online files updated roughly every week. The vast majority of players are dead accounts, so the chance of seeing an account, that is 
- at or below your own level
- is active
- has items, that you need
- decides to change exactly the items, that you need

is pretty small. As I said, this will basically just be a possible problem for servers, that are just a month or so old, at which point manually crawling can still just be done in a few minutes, if you want.

The benefits of having multiple different crawling directions, starting & end points is just not worth the complexity and the time this would take. Especially when you consider, that this would make sharing HoF files even harder, as they would all have different orders and limits.

There is a dedicated Hof Sharing issue, if you have any more questions.

**Comment by Usaksport** [comment]
Ohh yeah my fault.  Totally agree with you. Many thanks for pushing me in the right direction ;) 
Just to ask is there also a possibility to donate to  you for your work?

**Comment by the-marenga** [comment]
Sure, if you wan't to support me, I just made a donation page for that 😄:

https://ko-fi.com/marenga

**Comment by Usaksport** [comment]
done ;)
