### ISSUE TITLE
Crawl threads/account question

### ISSUE THREAD

**Issue by PilarczykM** [the-marenga/sf-scrapbook-helper#13]
[Question]
Is there a specific reason why application allows up to10 thread `clamp_range(1..=10)` ? It's because of security (crawling to be more hidden) or memory management?

**Comment by the-marenga** [comment]
[TLDR]
Yes, it is to be more hidden

[Long Answer]
The communication to the server is inherently sequentially. Each acount has to wait until its request is finished, before it can send the next one. That means to improve crawling speed we need more accounts, so each thread creates its own account on the server. I do not expect most people to read, or obey any form of guide, so if there was no limit, I would expect people to just put the number of accounts as high as their internet speed would allow it to (roughly 200-1000), or even higher. At that point a handful of people would be enough to completely flood servers with junk accounts. That would A: get them banned and B: get this tool here taked down I would assume. As such, I just enforce a limit of 10 to keep the load on the server as low as possible, whilst being able to crawl at a reasonable speed.

---

For the future I was thinking about just providing a precrawled list of players, so nobody has to crawl anymore, but I am currently sick, so my plan of imlpementing that this week is probably not happening.
