### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by Headstrike** [the-marenga/sf-scrapbook-helper#27]
Hey,

first of all I really love your Helper. 
Now my idea: 
I have multiple Accounts and I would love to get the feature that I can search and attack with multiple accounts simultaneously. That would be super helpful.

Best regards

**Comment by the-marenga** [comment]
> first of all I really love your Helper.

Thanks!

>  I would love to get the feature that I can search and attack with multiple accounts simultaneously

The next release will contains support for handling multiple accounts simultaneously. It is already implemented in my local version of the code. It is a total rewrite of the entire program though, so it might take me a few days, until I finish and I release that version

**Comment by Headstrike** [comment]
If you need help with testing. I would be happy to help.

**Comment by the-marenga** [comment]
> If you need help with testing. I would be happy to help.

Sure, during the 1.0 release someone was unable to start the tool from anywhere but the desktop, so testing this on other machines sounds like a great idea. If you experience any errors, anything does not work as expected, or is confusing  to understand, feel free to give feedback:

[Scrapbook Helper.zip](https://github.com/the-marenga/sf-scrapbook-helper/files/14538451/Scrapbook.Helper.zip)

The underworld tab and logging out are not implemented yet and the number inputs are weird, but otherwise this should work.

**Comment by Headstrike** [comment]
Hey thanks for letting me test the version. 
I have found very few things:
I have had some trouble with HoF entries loading or showing up on s43-DE and s10-EU. Found some entries in the older version.
When clicking on SSO and then on my SSO-Account. I get the the overview of all the characters. The I have to click on "Back" to see the overview. I would prefer it the other way round.
I would personally put the charakter name and world above the other ctats (over Mushrooms)


**Features I would like to see in the future:**
1. Missing items per Category per Account (Warrior, Mage, Scout)
2. Login with all characters with one click - "Login All"
3. While hovering over the count of the missing items, display the Item name
4. More information on the overview page. Maybe have it in a grid layout with informaton like, Last attack time, next attack time, missing items per category, fo each charakter.

All in all a pretty good update. Keep if going and let me know if I can help again.

**Comment by the-marenga** [comment]
Hey, thanks for the testing! I am going to look into the loading issue. And yes, the overall ui navigation could certainly be simplified.

> Missing items per Category per Account (Warrior, Mage, Scout)

I could add a "items found per class/item type", but AFAIK there is no "total items count", that I can get from the server, so I would have to hard-code a count for each category. That means whenever S&F adds new items, the amount of missing items would be out of date and people could get a wrong impression of how full their scrapbook is. I will have to think about how/if I can solve that, but for the time being the best I could do is just the amount collected, not how much is missing.

> Login with all characters with one click - "Login All"

Yeah, that and "login on startup" + "save player settings (auto attack)" are for sure needed and on my radar for the future 

 > While hovering over the count of the missing items, display the Item name

Pretty sure, that if I add a list of all item names to the program, that would infringe on playagames copyright. The api sadly only supplies a number. Not sure if they would take this tool here down immediately, or only, once I start using their images, but I don't want to take the risk either way. That is (probably) one of the main reasons, why CrawlerNG & MFBot are not open source.

> More information on the overview page. Maybe have it in a grid layout with informaton like, Last attack time, next attack time

Yes, for sure, that sounds great


Thanks again for testing
