### ISSUE TITLE
Can't login to my account

### ISSUE THREAD

**Issue by Skemax19** [the-marenga/sf-scrapbook-helper#28]
I tried the app, but it tells me server error password wrong. (Password is right.. Tested it several times)
I am trying to log in to s10.sfgame.eu

**Comment by the-marenga** [comment]
Just tested my account there and it seems to work fine. I don't expect you to give me your password to debug this, but do you have any other insight, what might cause this? Weird characters in the password? Very long/short password? What kind of account are you using (SF/Regular)?

**Comment by the-marenga** [comment]
The most likely thing is, that this character is connectet to an sf account and you are trying to login via the regular login, as that would be the error message from the server

**Comment by Skemax19** [comment]
Yeah i think its on me. I tried the SOO login and it works like butter. Thank you very much :)
Keep up the good work ! :)
