### ISSUE TITLE
[Bug] "Logout" removes the previous character from the SSO list

### ISSUE THREAD

**Issue by Johandreasson** [the-marenga/sf-scrapbook-helper#50]
**Describe the bug**
When you logout from the app using the button the logged out character is removed from the list under "SSO Chars".
The character reappears after you restart the app.

The log file doesn't give any hints towards the missing character.

**Comment by the-marenga** [comment]
Yeah, it currently works the same way for normal and SSO accounts, they are just removed. Adding SSO chars back to the available SSO chars list seems like a more appropriate thing to do though, you are right. I am going to work on that for the upcoming release
