### ISSUE TITLE
[Bug] "Logging in" loop

### ISSUE THREAD

**Issue by B0risz** [the-marenga/sf-scrapbook-helper#55]
**Describe the bug**
The Bug of a "Logging in" loop, which breaks the Program, until restart.

**To Reproduce**
1. Login
2. Pick any fight that has "???" as Attributes
3. Boom, you're seeing a "Logging in" text and cant do anything about it.

**Expected behavior**
The problem is, that the program somehow finds users that are not on the selected gameserver, and tries to attack them
(can be proven by searching the player in the Hall of Fame manually).

**Screenshots**
![Screenshot_152](https://github.com/the-marenga/sf-scrapbook-helper/assets/62288723/e853c8d2-be38-412f-9ae8-1d5dfa0c024a)

**Comment by the-marenga** [comment]
Yeah, the ??? means, they were originally fetched by me (roughly a month ago) and between then and now, they have then removed their account, which means attacking them is an invalid action.

I guess I should both 
- update the online HoF and 
- fix this by hiding accounts, that are not available anymore. 

Thanks for the report
