### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Andxev0** [the-marenga/sf-scrapbook-helper#7]
Hey i couldnt find the suggestions tab where i could add it, my question would be is it possible to maybe make an config file where you can add a link like from a private sf game server and make it work there, would that be possible, just asking great work so far, it works like a charm :D

**Comment by the-marenga** [comment]
Thanks! I have no experience with private servers, so just a few quick notes/questions: 
- Can they not already be reached, if you put the server url in the current login screen?
- If not, then I do not really understand, how a config file would change anything? That would seem more like a login and not like config issue.
- Does connecting to private servers require more/other login information? 
- Do they use an older/different version of the game?
- Could you provide me with a link/invite to one, that you have in mind, so I could test anything regarding private servers myself?
- Would you want the config file just so you do not have to copy the url all the time? In that case, would you actually want some sort of account management/character history feature instead, where you can just select accounts you have successfully logged in to previously?

Quite a few questions, so if you are by any chance german, you can just answer in german, if that is quicker/easier for you

**Comment by Andxev0** [comment]
ahh ich sehs jetzt, ich glaube infach das die alten privaten server zu alt sind, denn die haben ein anderen mechanismuss sich einzuloggen als die normalen server :D, ich probiere es aus war nur eine frage für die zukunft, ich will mir mit ein paar freunden einen privaten server erstellen zum testen, aber es sieht aus als ob das schwerer ist als gedacht ^^, danke für die schnelle antwort
