### ISSUE TITLE
[Bug] App loops after clicking on Auto Battle

### ISSUE THREAD

**Issue by S0Ius** [the-marenga/sf-scrapbook-helper#70]
**Describe the bug**
Everything works great until i click on Auto Battle checkbox. After that i got looped and can only see message saying _Logging in player again_. Only solution to this is restart program and manually clicking on fight after every 10 minutes.

**To Reproduce**
1. Go to 'scrapbook'
2. Click on 'Auto Battle'
3. Scroll down to ' --- '
4. See "Logging in player again"

**Screenshots**
![obraz_2024-05-08_071536934](https://github.com/the-marenga/sf-scrapbook-helper/assets/169184487/26e1a276-9de5-4f0b-bacd-b116532a6873)

**Machine (please complete the following information):**
 - OS:  Windows
 - Version v0.2.1

**Additional context**
I have 2 characters linked to a single sf account. One is working without any problems on Auto battle, and second character have the bug i've described above.

**Comment by the-marenga** [comment]
Can you upload your "helper.log" file? I think I have a good idea what the problem is, but I want to make sure

**Comment by S0Ius** [comment]
[helper.log](https://github.com/the-marenga/sf-scrapbook-helper/files/15251309/helper.log)
