### ISSUE TITLE
[Feature Request] Skip a person if you lost to them

### ISSUE THREAD

**Issue by HaskiJestem** [the-marenga/sf-scrapbook-helper#74]
Would love for you to create a checkbox with an option that lets you skip a person from a queue once you lost to them in the arena and fight with a next person on a queue 10 minutes later  instead of fighting with the same one and potentially losing about 10 times in a row.

I noticed later that there is a blacklist system but I would like if you can skip a person after a first lost battle already.

After thinking about it again, the best option would be to just add an input which would determine after how many loses you want to blacklist someone.

**Comment by the-marenga** [comment]
Yeah, adding an input field in the settings seems like a reasonable thing to me. I am going to do that for the next release
