### ISSUE TITLE
[Bug] Huge CPU usage after crawling finishes

### ISSUE THREAD

**Issue by nikonowiczp** [the-marenga/sf-scrapbook-helper#75]
**Describe the bug**
Program uses all of the CPU it can after the crawling finished (more than during crawling) and thread are set to 9

**To Reproduce**
1. Start app and login to character
2. Set threads to 9
3. Wait for crawling to finish
4. Don't change the threads back

**Expected behavior**
After crawling ends the CPU should not be used

**Machine (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 0.2.1 (commit 452b457c01d3a58fe6bb6f9b6da8b9fb5b09db34 ) - self compiled

**Additional context**
The CPU is not used extensively during crawling. My CPU was ~4% used when crawling, 99.6% after it stopped. I have a good CPU.
Changing the threads back to 1 or 0 fixes the issue. This can be a fix - after crawling finishes just set it back to 0.

When threads are set to 1 CPU is used around 10%, jumps down to 3 again after setting to 0. Infinite loop?

**Comment by the-marenga** [comment]
Hmm... strange, each thread should just be doing a basic sleep for a set amount, if there is nothing left to do. I will have to look into that soon, thanks for the report!

**Comment by the-marenga** [comment]
Oh, yeah, jesus christ. It seems like I forgot to add a headless check at one point and that cloned and auto-saved the entire HoF to disk.. every few seconds... for every thread... for every character...

Big thanks again for pointing that error out!
