### ISSUE TITLE
[Bug] HoK menu being strange

### ISSUE THREAD

**Issue by Hydriam** [the-marenga/sf-scrapbook-helper#79]
After attacking somone the hok part of menu is being flattens

Before : 
![Before](https://github.com/the-marenga/sf-scrapbook-helper/assets/163676548/3785c647-3547-4012-a8d6-ab09366bec71)
After : 
![After](https://github.com/the-marenga/sf-scrapbook-helper/assets/163676548/3d39cdba-fc7f-4242-b1ee-ecc1bed360fc)

 - OS: Windows 10
 - Version Latest 

(sorry for bad english)

**Comment by the-marenga** [comment]
Thanks for the report. This is mainly an issue of the GUI library I used. They seem to handle vertical space in combination with a scrollable area very weirdly. There is even a bug, where the entire tool crashes, if you make it small enough. 

For the next release, I have therefore increased the minimum size of the tool, to make sure there is enough space for everything to render. That *should* "fix" this issue for the time being. 

Feel free to tell me, if the issue still happens in the next release, which should come in the next few days 😄
