### ISSUE TITLE
[Bug] *Auto battle doesn't work*

### ISSUE THREAD

**Issue by KacperST** [the-marenga/sf-scrapbook-helper#83]
**Describe the bug**
Before the release I had an inifnite logging loop and could not use autobattle feature on f13.net. After updating to the newest release auto battle option doesn't do anything, It does not logging to account and doesn't battle anyone

**To Reproduce**
1. Go to 'account'
2. Click on 'auto battle'
3. Scroll down to 'x'

**Expected behavior**
Auto battle sould log in to my account and battle people every 10 min

**Screenshots**
![image](https://github.com/the-marenga/sf-scrapbook-helper/assets/92333794/450131b0-620a-430c-a065-123ec3d921ee)

**Machine (please complete the following information):**
 - OS: Winows 10
 - Version v0.2.2

**Additional context**

**Comment by the-marenga** [comment]
Could you upload the "helper.log" file, so that I can see what type of errors/warnings get produced?

**Comment by the-marenga** [comment]
Can you try to increase the "Threads" value to a value > 0?

**Comment by the-marenga** [comment]
And wait, until the list of targets has refreshed

**Comment by KacperST** [comment]
Thanks, it worked! Altough First when I logged in I had 1 thread and still had the bug, but after increasing threads to 20, the list refreshed and auto-battling work is working
