### ISSUE TITLE
Cant login anymore

### ISSUE THREAD

**Issue by Kalsaticar** [the-marenga/sf-scrapbook-helper#84]
After downloading the newest feature, I can't login anymore. It happened right after I logged into the scrapbook helper.

Whenever I try to login, it says "Error in the system" with "Cannot do this right now2"

or

"Server is currently being fused, you can play on the server tomorrow at 4PM CET"

which is only an issue for me on all the servers.

Maybe the caught me who knows? 

Be careful downloading the newest feature.

**Comment by the-marenga** [comment]
I guess the S&F servers were just down for a short period of time and the issue resolved itself, right?
