### ISSUE TITLE
[Question] auto pause?

### ISSUE THREAD

**Issue by beeikjo** [the-marenga/sf-scrapbook-helper#85]
I'm trying to crawl my scrapbook. but no matter how many threads I set up, the tool only crawls about a few hundred characters then stops for 50-60 seconds before continuing. So is this a bug or a feature? Because at this rate, it will probably take 1 day to complete this. I am sure that my transmission has absolutely no problems during use.
I had this problem a few weeks ago (or maybe more than a month ago) but thought it was temporary.
https://github.com/the-marenga/sf-scrapbook-helper/assets/46583655/e165d524-9779-4bd7-8f38-83d4a85c33e6

**Comment by the-marenga** [comment]
To quote the info from the readme&release pages:
> S&F added rate-limiting (200reqs/min), so the ability to manually crawl an entire server is limited for the foreseeable future. I will work on updating the pre-crawled player lists, so that this will largely not be required

The more interesting part is, that it somehow finished in 30 minutes for you, so there might be some times, where their limiting doesn't work. But yeah, the pausing after 200reqs is not something I can easily fix
