### ISSUE TITLE
Searching hof stops

### ISSUE THREAD

**Issue by abialek677** [the-marenga/sf-scrapbook-helper#86]
When i try to look through hof it stops at 200, then waits like 3 minutes, goes to 400 and so on.

When I used it earlier it worked flawlessly

![image](https://github.com/the-marenga/sf-scrapbook-helper/assets/161772119/bd336662-2d43-4235-b814-55e05a13003f)

**Comment by kamil041** [comment]
_S&F added rate-limiting (200reqs/min), so the ability to manually crawl an entire server is limited for the foreseeable future. I will work on updating the pre-crawled player lists, so that this will largely not be required_
Man, please, check release notes...
